// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: meta.proto

package internal

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type FieldMappingState int32

const (
	FieldMappingState_ACTIVE  FieldMappingState = 0
	FieldMappingState_DELETED FieldMappingState = 1
	FieldMappingState_RENAMED FieldMappingState = 2
)

var FieldMappingState_name = map[int32]string{
	0: "ACTIVE",
	1: "DELETED",
	2: "RENAMED",
}

var FieldMappingState_value = map[string]int32{
	"ACTIVE":  0,
	"DELETED": 1,
	"RENAMED": 2,
}

func (x FieldMappingState) String() string {
	return proto.EnumName(FieldMappingState_name, int32(x))
}

func (FieldMappingState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{0}
}

type MeasurementMappingState int32

const (
	MeasurementMappingState_MEASUREMENT_ACTIVE  MeasurementMappingState = 0
	MeasurementMappingState_MEASUREMENT_DELETED MeasurementMappingState = 1
	MeasurementMappingState_MEASUREMENT_RENAMED MeasurementMappingState = 2
)

var MeasurementMappingState_name = map[int32]string{
	0: "MEASUREMENT_ACTIVE",
	1: "MEASUREMENT_DELETED",
	2: "MEASUREMENT_RENAMED",
}

var MeasurementMappingState_value = map[string]int32{
	"MEASUREMENT_ACTIVE":  0,
	"MEASUREMENT_DELETED": 1,
	"MEASUREMENT_RENAMED": 2,
}

func (x MeasurementMappingState) String() string {
	return proto.EnumName(MeasurementMappingState_name, int32(x))
}

func (MeasurementMappingState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{1}
}

type Series struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Tags                 []*Tag   `protobuf:"bytes,2,rep,name=Tags,proto3" json:"Tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Series) Reset()         { *m = Series{} }
func (m *Series) String() string { return proto.CompactTextString(m) }
func (*Series) ProtoMessage()    {}
func (*Series) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{0}
}
func (m *Series) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Series.Unmarshal(m, b)
}
func (m *Series) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Series.Marshal(b, m, deterministic)
}
func (m *Series) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Series.Merge(m, src)
}
func (m *Series) XXX_Size() int {
	return xxx_messageInfo_Series.Size(m)
}
func (m *Series) XXX_DiscardUnknown() {
	xxx_messageInfo_Series.DiscardUnknown(m)
}

var xxx_messageInfo_Series proto.InternalMessageInfo

func (m *Series) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Series) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

type Tag struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}
func (*Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{1}
}
func (m *Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tag.Unmarshal(m, b)
}
func (m *Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tag.Marshal(b, m, deterministic)
}
func (m *Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag.Merge(m, src)
}
func (m *Tag) XXX_Size() int {
	return xxx_messageInfo_Tag.Size(m)
}
func (m *Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Tag proto.InternalMessageInfo

func (m *Tag) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Tag) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type MeasurementFields struct {
	Name                 []byte          `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Fields               []*Field        `protobuf:"bytes,2,rep,name=Fields,proto3" json:"Fields,omitempty"`
	Mappings             []*FieldMapping `protobuf:"bytes,3,rep,name=Mappings,proto3" json:"Mappings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MeasurementFields) Reset()         { *m = MeasurementFields{} }
func (m *MeasurementFields) String() string { return proto.CompactTextString(m) }
func (*MeasurementFields) ProtoMessage()    {}
func (*MeasurementFields) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{2}
}
func (m *MeasurementFields) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeasurementFields.Unmarshal(m, b)
}
func (m *MeasurementFields) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeasurementFields.Marshal(b, m, deterministic)
}
func (m *MeasurementFields) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeasurementFields.Merge(m, src)
}
func (m *MeasurementFields) XXX_Size() int {
	return xxx_messageInfo_MeasurementFields.Size(m)
}
func (m *MeasurementFields) XXX_DiscardUnknown() {
	xxx_messageInfo_MeasurementFields.DiscardUnknown(m)
}

var xxx_messageInfo_MeasurementFields proto.InternalMessageInfo

func (m *MeasurementFields) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *MeasurementFields) GetFields() []*Field {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *MeasurementFields) GetMappings() []*FieldMapping {
	if m != nil {
		return m.Mappings
	}
	return nil
}

type Field struct {
	Name                 []byte   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Type                 int32    `protobuf:"varint,2,opt,name=Type,proto3" json:"Type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Field) Reset()         { *m = Field{} }
func (m *Field) String() string { return proto.CompactTextString(m) }
func (*Field) ProtoMessage()    {}
func (*Field) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{3}
}
func (m *Field) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field.Unmarshal(m, b)
}
func (m *Field) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field.Marshal(b, m, deterministic)
}
func (m *Field) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field.Merge(m, src)
}
func (m *Field) XXX_Size() int {
	return xxx_messageInfo_Field.Size(m)
}
func (m *Field) XXX_DiscardUnknown() {
	xxx_messageInfo_Field.DiscardUnknown(m)
}

var xxx_messageInfo_Field proto.InternalMessageInfo

func (m *Field) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *Field) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

type FieldMapping struct {
	UserName             string            `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"`
	InternalName         string            `protobuf:"bytes,2,opt,name=InternalName,proto3" json:"InternalName,omitempty"`
	Version              int64             `protobuf:"varint,3,opt,name=Version,proto3" json:"Version,omitempty"`
	State                FieldMappingState `protobuf:"varint,4,opt,name=State,proto3,enum=tsdb.FieldMappingState" json:"State,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *FieldMapping) Reset()         { *m = FieldMapping{} }
func (m *FieldMapping) String() string { return proto.CompactTextString(m) }
func (*FieldMapping) ProtoMessage()    {}
func (*FieldMapping) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{4}
}
func (m *FieldMapping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldMapping.Unmarshal(m, b)
}
func (m *FieldMapping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldMapping.Marshal(b, m, deterministic)
}
func (m *FieldMapping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldMapping.Merge(m, src)
}
func (m *FieldMapping) XXX_Size() int {
	return xxx_messageInfo_FieldMapping.Size(m)
}
func (m *FieldMapping) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldMapping.DiscardUnknown(m)
}

var xxx_messageInfo_FieldMapping proto.InternalMessageInfo

func (m *FieldMapping) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *FieldMapping) GetInternalName() string {
	if m != nil {
		return m.InternalName
	}
	return ""
}

func (m *FieldMapping) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *FieldMapping) GetState() FieldMappingState {
	if m != nil {
		return m.State
	}
	return FieldMappingState_ACTIVE
}

type MeasurementFieldSet struct {
	Measurements         []*MeasurementFields `protobuf:"bytes,1,rep,name=Measurements,proto3" json:"Measurements,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MeasurementFieldSet) Reset()         { *m = MeasurementFieldSet{} }
func (m *MeasurementFieldSet) String() string { return proto.CompactTextString(m) }
func (*MeasurementFieldSet) ProtoMessage()    {}
func (*MeasurementFieldSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{5}
}
func (m *MeasurementFieldSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeasurementFieldSet.Unmarshal(m, b)
}
func (m *MeasurementFieldSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeasurementFieldSet.Marshal(b, m, deterministic)
}
func (m *MeasurementFieldSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeasurementFieldSet.Merge(m, src)
}
func (m *MeasurementFieldSet) XXX_Size() int {
	return xxx_messageInfo_MeasurementFieldSet.Size(m)
}
func (m *MeasurementFieldSet) XXX_DiscardUnknown() {
	xxx_messageInfo_MeasurementFieldSet.DiscardUnknown(m)
}

var xxx_messageInfo_MeasurementFieldSet proto.InternalMessageInfo

func (m *MeasurementFieldSet) GetMeasurements() []*MeasurementFields {
	if m != nil {
		return m.Measurements
	}
	return nil
}

// FieldMappingSet stores centralized field mappings per database
type FieldMappingSet struct {
	Measurements         []*FieldMappingMeasurement `protobuf:"bytes,1,rep,name=Measurements,proto3" json:"Measurements,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *FieldMappingSet) Reset()         { *m = FieldMappingSet{} }
func (m *FieldMappingSet) String() string { return proto.CompactTextString(m) }
func (*FieldMappingSet) ProtoMessage()    {}
func (*FieldMappingSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{6}
}
func (m *FieldMappingSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldMappingSet.Unmarshal(m, b)
}
func (m *FieldMappingSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldMappingSet.Marshal(b, m, deterministic)
}
func (m *FieldMappingSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldMappingSet.Merge(m, src)
}
func (m *FieldMappingSet) XXX_Size() int {
	return xxx_messageInfo_FieldMappingSet.Size(m)
}
func (m *FieldMappingSet) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldMappingSet.DiscardUnknown(m)
}

var xxx_messageInfo_FieldMappingSet proto.InternalMessageInfo

func (m *FieldMappingSet) GetMeasurements() []*FieldMappingMeasurement {
	if m != nil {
		return m.Measurements
	}
	return nil
}

type FieldMappingMeasurement struct {
	Name                 []byte          `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Mappings             []*FieldMapping `protobuf:"bytes,2,rep,name=Mappings,proto3" json:"Mappings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *FieldMappingMeasurement) Reset()         { *m = FieldMappingMeasurement{} }
func (m *FieldMappingMeasurement) String() string { return proto.CompactTextString(m) }
func (*FieldMappingMeasurement) ProtoMessage()    {}
func (*FieldMappingMeasurement) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{7}
}
func (m *FieldMappingMeasurement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldMappingMeasurement.Unmarshal(m, b)
}
func (m *FieldMappingMeasurement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldMappingMeasurement.Marshal(b, m, deterministic)
}
func (m *FieldMappingMeasurement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldMappingMeasurement.Merge(m, src)
}
func (m *FieldMappingMeasurement) XXX_Size() int {
	return xxx_messageInfo_FieldMappingMeasurement.Size(m)
}
func (m *FieldMappingMeasurement) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldMappingMeasurement.DiscardUnknown(m)
}

var xxx_messageInfo_FieldMappingMeasurement proto.InternalMessageInfo

func (m *FieldMappingMeasurement) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *FieldMappingMeasurement) GetMappings() []*FieldMapping {
	if m != nil {
		return m.Mappings
	}
	return nil
}

type MeasurementMapping struct {
	UserName             string                  `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"`
	InternalName         string                  `protobuf:"bytes,2,opt,name=InternalName,proto3" json:"InternalName,omitempty"`
	Version              int64                   `protobuf:"varint,3,opt,name=Version,proto3" json:"Version,omitempty"`
	State                MeasurementMappingState `protobuf:"varint,4,opt,name=State,proto3,enum=tsdb.MeasurementMappingState" json:"State,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *MeasurementMapping) Reset()         { *m = MeasurementMapping{} }
func (m *MeasurementMapping) String() string { return proto.CompactTextString(m) }
func (*MeasurementMapping) ProtoMessage()    {}
func (*MeasurementMapping) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{8}
}
func (m *MeasurementMapping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeasurementMapping.Unmarshal(m, b)
}
func (m *MeasurementMapping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeasurementMapping.Marshal(b, m, deterministic)
}
func (m *MeasurementMapping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeasurementMapping.Merge(m, src)
}
func (m *MeasurementMapping) XXX_Size() int {
	return xxx_messageInfo_MeasurementMapping.Size(m)
}
func (m *MeasurementMapping) XXX_DiscardUnknown() {
	xxx_messageInfo_MeasurementMapping.DiscardUnknown(m)
}

var xxx_messageInfo_MeasurementMapping proto.InternalMessageInfo

func (m *MeasurementMapping) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *MeasurementMapping) GetInternalName() string {
	if m != nil {
		return m.InternalName
	}
	return ""
}

func (m *MeasurementMapping) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *MeasurementMapping) GetState() MeasurementMappingState {
	if m != nil {
		return m.State
	}
	return MeasurementMappingState_MEASUREMENT_ACTIVE
}

type MeasurementMappingSet struct {
	Mappings             []*MeasurementMapping `protobuf:"bytes,1,rep,name=Mappings,proto3" json:"Mappings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *MeasurementMappingSet) Reset()         { *m = MeasurementMappingSet{} }
func (m *MeasurementMappingSet) String() string { return proto.CompactTextString(m) }
func (*MeasurementMappingSet) ProtoMessage()    {}
func (*MeasurementMappingSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b5ea8fe65782bcc, []int{9}
}
func (m *MeasurementMappingSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeasurementMappingSet.Unmarshal(m, b)
}
func (m *MeasurementMappingSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeasurementMappingSet.Marshal(b, m, deterministic)
}
func (m *MeasurementMappingSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeasurementMappingSet.Merge(m, src)
}
func (m *MeasurementMappingSet) XXX_Size() int {
	return xxx_messageInfo_MeasurementMappingSet.Size(m)
}
func (m *MeasurementMappingSet) XXX_DiscardUnknown() {
	xxx_messageInfo_MeasurementMappingSet.DiscardUnknown(m)
}

var xxx_messageInfo_MeasurementMappingSet proto.InternalMessageInfo

func (m *MeasurementMappingSet) GetMappings() []*MeasurementMapping {
	if m != nil {
		return m.Mappings
	}
	return nil
}

func init() {
	proto.RegisterEnum("tsdb.FieldMappingState", FieldMappingState_name, FieldMappingState_value)
	proto.RegisterEnum("tsdb.MeasurementMappingState", MeasurementMappingState_name, MeasurementMappingState_value)
	proto.RegisterType((*Series)(nil), "tsdb.Series")
	proto.RegisterType((*Tag)(nil), "tsdb.Tag")
	proto.RegisterType((*MeasurementFields)(nil), "tsdb.MeasurementFields")
	proto.RegisterType((*Field)(nil), "tsdb.Field")
	proto.RegisterType((*FieldMapping)(nil), "tsdb.FieldMapping")
	proto.RegisterType((*MeasurementFieldSet)(nil), "tsdb.MeasurementFieldSet")
	proto.RegisterType((*FieldMappingSet)(nil), "tsdb.FieldMappingSet")
	proto.RegisterType((*FieldMappingMeasurement)(nil), "tsdb.FieldMappingMeasurement")
	proto.RegisterType((*MeasurementMapping)(nil), "tsdb.MeasurementMapping")
	proto.RegisterType((*MeasurementMappingSet)(nil), "tsdb.MeasurementMappingSet")
}

func init() { proto.RegisterFile("meta.proto", fileDescriptor_3b5ea8fe65782bcc) }

var fileDescriptor_3b5ea8fe65782bcc = []byte{
	// 484 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xc1, 0x6a, 0xdb, 0x40,
	0x10, 0xad, 0x2c, 0xd9, 0x49, 0xc6, 0xa6, 0x75, 0x26, 0x6d, 0xbd, 0x14, 0x0c, 0x46, 0xbd, 0x98,
	0xd0, 0xc8, 0x90, 0xf4, 0x12, 0x7a, 0x72, 0xeb, 0x2d, 0x84, 0x56, 0x3e, 0xac, 0x15, 0x1f, 0x0a,
	0xa5, 0xac, 0xe3, 0xa9, 0x2a, 0xb0, 0x65, 0xa3, 0x5d, 0x43, 0x03, 0xfd, 0x8f, 0x7e, 0x40, 0x7f,
	0xb4, 0x78, 0xa5, 0x28, 0xb2, 0x25, 0x43, 0x2f, 0xbd, 0xcd, 0xcc, 0x7b, 0xf3, 0x66, 0x67, 0x9e,
	0x10, 0xc0, 0x92, 0xb4, 0xf4, 0xd6, 0xc9, 0x4a, 0xaf, 0xd0, 0xd1, 0x6a, 0x3e, 0x73, 0xaf, 0xa1,
	0x31, 0xa1, 0x24, 0x22, 0x85, 0x6d, 0xb0, 0x3f, 0xd1, 0x3d, 0xb3, 0x7a, 0x56, 0xff, 0x44, 0x6c,
	0x43, 0xec, 0x82, 0x13, 0xc8, 0x50, 0xb1, 0x5a, 0xcf, 0xee, 0x37, 0x2f, 0x4f, 0xbc, 0x6d, 0x83,
	0x17, 0xc8, 0x50, 0x98, 0xb2, 0x7b, 0x01, 0x76, 0x20, 0xc3, 0x8a, 0xbe, 0xe7, 0x50, 0x9f, 0xca,
	0xc5, 0x86, 0x58, 0xcd, 0xd4, 0xd2, 0xc4, 0xfd, 0x05, 0xa7, 0x3e, 0x49, 0xb5, 0x49, 0x68, 0x49,
	0xb1, 0xfe, 0x18, 0xd1, 0x62, 0xae, 0x10, 0xc1, 0x19, 0xcb, 0x25, 0x99, 0xee, 0x96, 0x30, 0x31,
	0xbe, 0x86, 0x46, 0x8a, 0x66, 0x83, 0x9b, 0xe9, 0x60, 0x53, 0x13, 0x19, 0x84, 0x1e, 0x1c, 0xfb,
	0x72, 0xbd, 0x8e, 0xe2, 0x50, 0x31, 0xdb, 0xd0, 0xb0, 0x40, 0xcb, 0x20, 0x91, 0x73, 0xdc, 0x01,
	0xd4, 0x0d, 0x52, 0x39, 0x11, 0xc1, 0x09, 0xee, 0xd7, 0xe9, 0x7b, 0xeb, 0xc2, 0xc4, 0xee, 0x6f,
	0x0b, 0x5a, 0x45, 0x2d, 0x7c, 0x05, 0xc7, 0xb7, 0x8a, 0x92, 0xbc, 0xf9, 0x44, 0xe4, 0x39, 0xba,
	0xd0, 0xba, 0x89, 0x35, 0x25, 0xb1, 0x5c, 0x18, 0x3c, 0x5d, 0x7c, 0xa7, 0x86, 0x0c, 0x8e, 0xa6,
	0x94, 0xa8, 0x68, 0x15, 0x33, 0xbb, 0x67, 0xf5, 0x6d, 0xf1, 0x90, 0xe2, 0x05, 0xd4, 0x27, 0x5a,
	0x6a, 0x62, 0x4e, 0xcf, 0xea, 0x3f, 0xbd, 0xec, 0x94, 0x17, 0x31, 0xb0, 0x48, 0x59, 0xae, 0x80,
	0xb3, 0xfd, 0x43, 0x4e, 0x48, 0xe3, 0x3b, 0x68, 0x15, 0xca, 0x8a, 0x59, 0xe6, 0x2a, 0x99, 0x58,
	0xe9, 0xf2, 0x62, 0x87, 0xec, 0x06, 0xf0, 0x6c, 0x67, 0x1e, 0x69, 0x1c, 0x56, 0xea, 0x75, 0xcb,
	0x8f, 0x2b, 0xb0, 0xf6, 0x54, 0xbf, 0x42, 0xe7, 0x00, 0xb1, 0xd2, 0x86, 0xa2, 0xa7, 0xb5, 0x7f,
	0xf0, 0xf4, 0x8f, 0x05, 0x58, 0xd0, 0xfc, 0xff, 0x46, 0x5d, 0xed, 0x1a, 0xd5, 0x2d, 0xdd, 0xb6,
	0xca, 0x2e, 0x1f, 0x5e, 0x54, 0x30, 0x48, 0xe3, 0xdb, 0xc2, 0xba, 0xe9, 0x71, 0xd9, 0x21, 0xc1,
	0xc7, 0xa5, 0xcf, 0xaf, 0xe1, 0xb4, 0xf4, 0x65, 0x20, 0x40, 0x63, 0xf8, 0x21, 0xb8, 0x99, 0xf2,
	0xf6, 0x13, 0x6c, 0xc2, 0xd1, 0x88, 0x7f, 0xe6, 0x01, 0x1f, 0xb5, 0xad, 0x6d, 0x22, 0xf8, 0x78,
	0xe8, 0xf3, 0x51, 0xbb, 0x76, 0x7e, 0x07, 0x9d, 0x03, 0x6f, 0xc5, 0x97, 0x80, 0x3e, 0x1f, 0x4e,
	0x6e, 0x05, 0xf7, 0xf9, 0x38, 0xf8, 0x96, 0x8b, 0x75, 0xe0, 0xac, 0x58, 0x7f, 0x14, 0xde, 0x03,
	0xf2, 0x21, 0xef, 0xbd, 0x2f, 0x6f, 0xc2, 0x48, 0xff, 0xd8, 0xcc, 0xbc, 0xbb, 0xd5, 0x72, 0x10,
	0xc5, 0xdf, 0x17, 0x9b, 0x9f, 0x73, 0xa9, 0xe5, 0x43, 0x38, 0x1b, 0x6c, 0x77, 0x1c, 0x44, 0xd9,
	0xc5, 0x67, 0x0d, 0xf3, 0x37, 0xba, 0xfa, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x53, 0x9f, 0x8b, 0xd5,
	0x9b, 0x04, 0x00, 0x00,
}
