// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: meta.proto

package internal

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Series struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Tags                 []*Tag   `protobuf:"bytes,2,rep,name=Tags,proto3" json:"Tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Series) Reset()         { *m = Series{} }
func (m *Series) String() string { return proto.CompactTextString(m) }
func (*Series) ProtoMessage()    {}
func (*Series) Descriptor() ([]byte, []int) {
	return fileDescriptor_59b0956366e72083, []int{0}
}
func (m *Series) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Series.Unmarshal(m, b)
}
func (m *Series) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Series.Marshal(b, m, deterministic)
}
func (m *Series) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Series.Merge(m, src)
}
func (m *Series) XXX_Size() int {
	return xxx_messageInfo_Series.Size(m)
}
func (m *Series) XXX_DiscardUnknown() {
	xxx_messageInfo_Series.DiscardUnknown(m)
}

var xxx_messageInfo_Series proto.InternalMessageInfo

func (m *Series) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Series) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

type Tag struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}
func (*Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_59b0956366e72083, []int{1}
}
func (m *Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tag.Unmarshal(m, b)
}
func (m *Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tag.Marshal(b, m, deterministic)
}
func (m *Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag.Merge(m, src)
}
func (m *Tag) XXX_Size() int {
	return xxx_messageInfo_Tag.Size(m)
}
func (m *Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Tag proto.InternalMessageInfo

func (m *Tag) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Tag) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type MeasurementFields struct {
	Name                 []byte   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Fields               []*Field `protobuf:"bytes,2,rep,name=Fields,proto3" json:"Fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MeasurementFields) Reset()         { *m = MeasurementFields{} }
func (m *MeasurementFields) String() string { return proto.CompactTextString(m) }
func (*MeasurementFields) ProtoMessage()    {}
func (*MeasurementFields) Descriptor() ([]byte, []int) {
	return fileDescriptor_59b0956366e72083, []int{2}
}
func (m *MeasurementFields) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeasurementFields.Unmarshal(m, b)
}
func (m *MeasurementFields) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeasurementFields.Marshal(b, m, deterministic)
}
func (m *MeasurementFields) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeasurementFields.Merge(m, src)
}
func (m *MeasurementFields) XXX_Size() int {
	return xxx_messageInfo_MeasurementFields.Size(m)
}
func (m *MeasurementFields) XXX_DiscardUnknown() {
	xxx_messageInfo_MeasurementFields.DiscardUnknown(m)
}

var xxx_messageInfo_MeasurementFields proto.InternalMessageInfo

func (m *MeasurementFields) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *MeasurementFields) GetFields() []*Field {
	if m != nil {
		return m.Fields
	}
	return nil
}

type Field struct {
	Name                 []byte   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Type                 int32    `protobuf:"varint,2,opt,name=Type,proto3" json:"Type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Field) Reset()         { *m = Field{} }
func (m *Field) String() string { return proto.CompactTextString(m) }
func (*Field) ProtoMessage()    {}
func (*Field) Descriptor() ([]byte, []int) {
	return fileDescriptor_59b0956366e72083, []int{3}
}
func (m *Field) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field.Unmarshal(m, b)
}
func (m *Field) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field.Marshal(b, m, deterministic)
}
func (m *Field) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field.Merge(m, src)
}
func (m *Field) XXX_Size() int {
	return xxx_messageInfo_Field.Size(m)
}
func (m *Field) XXX_DiscardUnknown() {
	xxx_messageInfo_Field.DiscardUnknown(m)
}

var xxx_messageInfo_Field proto.InternalMessageInfo

func (m *Field) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *Field) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

type MeasurementFieldSet struct {
	Measurements         []*MeasurementFields `protobuf:"bytes,1,rep,name=Measurements,proto3" json:"Measurements,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MeasurementFieldSet) Reset()         { *m = MeasurementFieldSet{} }
func (m *MeasurementFieldSet) String() string { return proto.CompactTextString(m) }
func (*MeasurementFieldSet) ProtoMessage()    {}
func (*MeasurementFieldSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_59b0956366e72083, []int{4}
}
func (m *MeasurementFieldSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeasurementFieldSet.Unmarshal(m, b)
}
func (m *MeasurementFieldSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeasurementFieldSet.Marshal(b, m, deterministic)
}
func (m *MeasurementFieldSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeasurementFieldSet.Merge(m, src)
}
func (m *MeasurementFieldSet) XXX_Size() int {
	return xxx_messageInfo_MeasurementFieldSet.Size(m)
}
func (m *MeasurementFieldSet) XXX_DiscardUnknown() {
	xxx_messageInfo_MeasurementFieldSet.DiscardUnknown(m)
}

var xxx_messageInfo_MeasurementFieldSet proto.InternalMessageInfo

func (m *MeasurementFieldSet) GetMeasurements() []*MeasurementFields {
	if m != nil {
		return m.Measurements
	}
	return nil
}

func init() {
	proto.RegisterType((*Series)(nil), "tsdb.Series")
	proto.RegisterType((*Tag)(nil), "tsdb.Tag")
	proto.RegisterType((*MeasurementFields)(nil), "tsdb.MeasurementFields")
	proto.RegisterType((*Field)(nil), "tsdb.Field")
	proto.RegisterType((*MeasurementFieldSet)(nil), "tsdb.MeasurementFieldSet")
}

func init() { proto.RegisterFile("meta.proto", fileDescriptor_59b0956366e72083) }

var fileDescriptor_59b0956366e72083 = []byte{
	// 397 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0x4d, 0x6b, 0xe3, 0x30,
	0x10, 0x25, 0xb1, 0x13, 0x92, 0x89, 0x21, 0xbb, 0xca, 0x86, 0x98, 0x85, 0x40, 0xd0, 0x5e, 0x72,
	0xd8, 0xb5, 0xd9, 0x8f, 0xcb, 0xd2, 0x53, 0x4b, 0x69, 0x29, 0x25, 0x81, 0x2a, 0x6e, 0x0f, 0x85,
	0x1e, 0xe4, 0x46, 0x75, 0x0d, 0xb6, 0x63, 0x2c, 0x19, 0x1a, 0xe8, 0x8f, 0x2f, 0x96, 0x9c, 0x54,
	0xb1, 0x5d, 0xe8, 0x21, 0xb7, 0xd1, 0xbc, 0x37, 0x4f, 0x6f, 0x9e, 0x10, 0x8c, 0xc2, 0x44, 0xb0,
	0x2c, 0xa1, 0x91, 0x1b, 0x33, 0x41, 0x9d, 0x34, 0xdb, 0x88, 0x0d, 0x32, 0x05, 0x5f, 0xfb, 0xf8,
	0x3f, 0x74, 0x57, 0x2c, 0x0b, 0x19, 0x47, 0x5f, 0xc0, 0xb8, 0x66, 0x5b, 0xbb, 0x35, 0x6b, 0xcd,
	0xfb, 0xa4, 0x28, 0xd1, 0x14, 0x4c, 0x8f, 0x06, 0xdc, 0x6e, 0xcf, 0x8c, 0xf9, 0xe0, 0x4f, 0xdf,
	0x29, 0x06, 0x1c, 0x8f, 0x06, 0x44, 0xb6, 0xf1, 0x2f, 0x30, 0x3c, 0x1a, 0x34, 0xcc, 0x7d, 0x83,
	0xce, 0x1d, 0x8d, 0x72, 0x66, 0xb7, 0x65, 0x4f, 0x1d, 0xf0, 0x2b, 0x7c, 0x5d, 0x30, 0xca, 0xf3,
	0x8c, 0xc5, 0x2c, 0x11, 0x17, 0x21, 0x8b, 0xd6, 0x1c, 0x21, 0x30, 0x97, 0x34, 0x66, 0x72, 0xda,
	0x22, 0xb2, 0x46, 0x3f, 0xa0, 0xab, 0xd0, 0xf2, 0xe2, 0x81, 0xba, 0x58, 0xf6, 0x48, 0x09, 0x21,
	0x07, 0x7a, 0x0b, 0x9a, 0xa6, 0x61, 0x12, 0x70, 0xdb, 0x90, 0x34, 0xa4, 0xd1, 0x4a, 0x88, 0xec,
	0x39, 0xd8, 0x85, 0x8e, 0x44, 0x1a, 0x6f, 0x44, 0x60, 0x7a, 0xdb, 0x54, 0xf9, 0xed, 0x10, 0x59,
	0xe3, 0x25, 0x58, 0xba, 0x14, 0xfa, 0x0e, 0xbd, 0x5b, 0xce, 0xb2, 0xfd, 0x6c, 0x9f, 0xec, 0xcf,
	0x08, 0x83, 0x75, 0x55, 0x26, 0x2c, 0x71, 0xb5, 0xf7, 0x41, 0x0f, 0x13, 0x18, 0x55, 0xd7, 0x5f,
	0x31, 0x81, 0x4e, 0xc0, 0xd2, 0xda, 0xdc, 0x6e, 0xc9, 0x5d, 0x26, 0x6a, 0x97, 0x5a, 0x5e, 0xe4,
	0x80, 0x8c, 0x3d, 0x18, 0xea, 0x1e, 0x0b, 0xbd, 0xd3, 0x46, 0xbd, 0x69, 0x3d, 0x1b, 0x8d, 0x55,
	0x51, 0x7d, 0x80, 0xc9, 0x07, 0xc4, 0xc6, 0xf0, 0xf4, 0x97, 0x68, 0x7f, 0xe2, 0x25, 0x3c, 0x40,
	0x9a, 0xe4, 0xb1, 0xe2, 0x5d, 0xc0, 0xb8, 0xae, 0x5a, 0x04, 0xf2, 0x4f, 0xb3, 0xa7, 0xc2, 0xb0,
	0x6b, 0xe1, 0xd6, 0x4d, 0xde, 0xc0, 0xf0, 0x9c, 0x0a, 0xea, 0x53, 0xce, 0x8e, 0xe5, 0xf0, 0x12,
	0x50, 0x45, 0xb2, 0xb0, 0xf7, 0xbb, 0x66, 0x6f, 0xac, 0xec, 0x55, 0xb8, 0xef, 0xde, 0xce, 0x9c,
	0xfb, 0x9f, 0x41, 0x28, 0x9e, 0x73, 0xdf, 0x79, 0xdc, 0xc4, 0x6e, 0x98, 0x3c, 0x45, 0xf9, 0xcb,
	0x9a, 0x0a, 0xba, 0x2b, 0x7d, 0xb7, 0x10, 0x70, 0x77, 0x7f, 0xde, 0xef, 0xca, 0xff, 0xfe, 0xf7,
	0x2d, 0x00, 0x00, 0xff, 0xff, 0x5a, 0x37, 0x2f, 0x7d, 0x06, 0x04, 0x00, 0x00,
}
