syntax = "proto3";

package tsdb;

option go_package = "github.com/influxdata/influxdb/tsdb/internal";

//========================================================================
//
// Metadata
//
//========================================================================

message Series {
  string Key = 1;
  repeated Tag Tags = 2;
}

message Tag {
  string Key = 1;
  string Value = 2;
}

message MeasurementFields {
  bytes Name = 1;
  repeated Field Fields = 2;
  repeated FieldMapping Mappings = 3;  // NEW
}

message Field {
  bytes Name = 1;
  int32 Type = 2;
}

message FieldMapping {
  string UserName = 1;     // User-facing name
  string InternalName = 2; // Internal storage name (seriesKey#!~#internalName)
}

message MeasurementFieldSet {
	repeated MeasurementFields Measurements = 1;
}

