// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: meta.proto

package internal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FieldMappingState int32

const (
	FieldMappingState_ACTIVE  FieldMappingState = 0
	FieldMappingState_DELETED FieldMappingState = 1
	FieldMappingState_RENAMED FieldMappingState = 2
)

// Enum value maps for FieldMappingState.
var (
	FieldMappingState_name = map[int32]string{
		0: "ACTIVE",
		1: "DELETED",
		2: "RENAMED",
	}
	FieldMappingState_value = map[string]int32{
		"ACTIVE":  0,
		"DELETED": 1,
		"RENAMED": 2,
	}
)

func (x FieldMappingState) Enum() *FieldMappingState {
	p := new(FieldMappingState)
	*p = x
	return p
}

func (x FieldMappingState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FieldMappingState) Descriptor() protoreflect.EnumDescriptor {
	return file_meta_proto_enumTypes[0].Descriptor()
}

func (FieldMappingState) Type() protoreflect.EnumType {
	return &file_meta_proto_enumTypes[0]
}

func (x FieldMappingState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FieldMappingState.Descriptor instead.
func (FieldMappingState) EnumDescriptor() ([]byte, []int) {
	return file_meta_proto_rawDescGZIP(), []int{0}
}

type Series struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Tags          []*Tag                 `protobuf:"bytes,2,rep,name=Tags,proto3" json:"Tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Series) Reset() {
	*x = Series{}
	mi := &file_meta_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Series) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Series) ProtoMessage() {}

func (x *Series) ProtoReflect() protoreflect.Message {
	mi := &file_meta_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Series.ProtoReflect.Descriptor instead.
func (*Series) Descriptor() ([]byte, []int) {
	return file_meta_proto_rawDescGZIP(), []int{0}
}

func (x *Series) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Series) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_meta_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_meta_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_meta_proto_rawDescGZIP(), []int{1}
}

func (x *Tag) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Tag) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type MeasurementFields struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          []byte                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Fields        []*Field               `protobuf:"bytes,2,rep,name=Fields,proto3" json:"Fields,omitempty"`
	Mappings      []*FieldMapping        `protobuf:"bytes,3,rep,name=Mappings,proto3" json:"Mappings,omitempty"` // NEW
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeasurementFields) Reset() {
	*x = MeasurementFields{}
	mi := &file_meta_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeasurementFields) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeasurementFields) ProtoMessage() {}

func (x *MeasurementFields) ProtoReflect() protoreflect.Message {
	mi := &file_meta_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeasurementFields.ProtoReflect.Descriptor instead.
func (*MeasurementFields) Descriptor() ([]byte, []int) {
	return file_meta_proto_rawDescGZIP(), []int{2}
}

func (x *MeasurementFields) GetName() []byte {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *MeasurementFields) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *MeasurementFields) GetMappings() []*FieldMapping {
	if x != nil {
		return x.Mappings
	}
	return nil
}

type Field struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          []byte                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Type          int32                  `protobuf:"varint,2,opt,name=Type,proto3" json:"Type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Field) Reset() {
	*x = Field{}
	mi := &file_meta_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_meta_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_meta_proto_rawDescGZIP(), []int{3}
}

func (x *Field) GetName() []byte {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *Field) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type FieldMapping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"`         // User-facing name
	InternalName  string                 `protobuf:"bytes,2,opt,name=InternalName,proto3" json:"InternalName,omitempty"` // Internal storage name (seriesKey#!~#internalName)
	Version       int64                  `protobuf:"varint,3,opt,name=Version,proto3" json:"Version,omitempty"`          // Monotonic version counter
	State         FieldMappingState      `protobuf:"varint,4,opt,name=State,proto3,enum=tsdb.FieldMappingState" json:"State,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldMapping) Reset() {
	*x = FieldMapping{}
	mi := &file_meta_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldMapping) ProtoMessage() {}

func (x *FieldMapping) ProtoReflect() protoreflect.Message {
	mi := &file_meta_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldMapping.ProtoReflect.Descriptor instead.
func (*FieldMapping) Descriptor() ([]byte, []int) {
	return file_meta_proto_rawDescGZIP(), []int{4}
}

func (x *FieldMapping) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *FieldMapping) GetInternalName() string {
	if x != nil {
		return x.InternalName
	}
	return ""
}

func (x *FieldMapping) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *FieldMapping) GetState() FieldMappingState {
	if x != nil {
		return x.State
	}
	return FieldMappingState_ACTIVE
}

type MeasurementFieldSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Measurements  []*MeasurementFields   `protobuf:"bytes,1,rep,name=Measurements,proto3" json:"Measurements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeasurementFieldSet) Reset() {
	*x = MeasurementFieldSet{}
	mi := &file_meta_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeasurementFieldSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeasurementFieldSet) ProtoMessage() {}

func (x *MeasurementFieldSet) ProtoReflect() protoreflect.Message {
	mi := &file_meta_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeasurementFieldSet.ProtoReflect.Descriptor instead.
func (*MeasurementFieldSet) Descriptor() ([]byte, []int) {
	return file_meta_proto_rawDescGZIP(), []int{5}
}

func (x *MeasurementFieldSet) GetMeasurements() []*MeasurementFields {
	if x != nil {
		return x.Measurements
	}
	return nil
}

var File_meta_proto protoreflect.FileDescriptor

const file_meta_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"meta.proto\x12\x04tsdb\"9\n" +
	"\x06Series\x12\x10\n" +
	"\x03Key\x18\x01 \x01(\tR\x03Key\x12\x1d\n" +
	"\x04Tags\x18\x02 \x03(\v2\t.tsdb.TagR\x04Tags\"-\n" +
	"\x03Tag\x12\x10\n" +
	"\x03Key\x18\x01 \x01(\tR\x03Key\x12\x14\n" +
	"\x05Value\x18\x02 \x01(\tR\x05Value\"|\n" +
	"\x11MeasurementFields\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\fR\x04Name\x12#\n" +
	"\x06Fields\x18\x02 \x03(\v2\v.tsdb.FieldR\x06Fields\x12.\n" +
	"\bMappings\x18\x03 \x03(\v2\x12.tsdb.FieldMappingR\bMappings\"/\n" +
	"\x05Field\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\fR\x04Name\x12\x12\n" +
	"\x04Type\x18\x02 \x01(\x05R\x04Type\"\x97\x01\n" +
	"\fFieldMapping\x12\x1a\n" +
	"\bUserName\x18\x01 \x01(\tR\bUserName\x12\"\n" +
	"\fInternalName\x18\x02 \x01(\tR\fInternalName\x12\x18\n" +
	"\aVersion\x18\x03 \x01(\x03R\aVersion\x12-\n" +
	"\x05State\x18\x04 \x01(\x0e2\x17.tsdb.FieldMappingStateR\x05State\"R\n" +
	"\x13MeasurementFieldSet\x12;\n" +
	"\fMeasurements\x18\x01 \x03(\v2\x17.tsdb.MeasurementFieldsR\fMeasurements*9\n" +
	"\x11FieldMappingState\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x00\x12\v\n" +
	"\aDELETED\x10\x01\x12\v\n" +
	"\aRENAMED\x10\x02B.Z,github.com/influxdata/influxdb/tsdb/internalb\x06proto3"

var (
	file_meta_proto_rawDescOnce sync.Once
	file_meta_proto_rawDescData []byte
)

func file_meta_proto_rawDescGZIP() []byte {
	file_meta_proto_rawDescOnce.Do(func() {
		file_meta_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meta_proto_rawDesc), len(file_meta_proto_rawDesc)))
	})
	return file_meta_proto_rawDescData
}

var file_meta_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_meta_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_meta_proto_goTypes = []any{
	(FieldMappingState)(0),      // 0: tsdb.FieldMappingState
	(*Series)(nil),              // 1: tsdb.Series
	(*Tag)(nil),                 // 2: tsdb.Tag
	(*MeasurementFields)(nil),   // 3: tsdb.MeasurementFields
	(*Field)(nil),               // 4: tsdb.Field
	(*FieldMapping)(nil),        // 5: tsdb.FieldMapping
	(*MeasurementFieldSet)(nil), // 6: tsdb.MeasurementFieldSet
}
var file_meta_proto_depIdxs = []int32{
	2, // 0: tsdb.Series.Tags:type_name -> tsdb.Tag
	4, // 1: tsdb.MeasurementFields.Fields:type_name -> tsdb.Field
	5, // 2: tsdb.MeasurementFields.Mappings:type_name -> tsdb.FieldMapping
	0, // 3: tsdb.FieldMapping.State:type_name -> tsdb.FieldMappingState
	3, // 4: tsdb.MeasurementFieldSet.Measurements:type_name -> tsdb.MeasurementFields
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_meta_proto_init() }
func file_meta_proto_init() {
	if File_meta_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meta_proto_rawDesc), len(file_meta_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meta_proto_goTypes,
		DependencyIndexes: file_meta_proto_depIdxs,
		EnumInfos:         file_meta_proto_enumTypes,
		MessageInfos:      file_meta_proto_msgTypes,
	}.Build()
	File_meta_proto = out.File
	file_meta_proto_goTypes = nil
	file_meta_proto_depIdxs = nil
}
